setup_kw_object = "OBJECT"
setup_kw_filter = "HIERARCH ESO INS FILT1 NAME"
setup_kw_type = "HIERARCH ESO DPR TYPE"
setup_kw_catg = "HIERARCH ESO DPR CATG"
setup_kw_dit = "HIERARCH ESO DET DIT"
setup_kw_ndit = "HIERARCH ESO DET NDIT"
setup_kw_mjd = "MJD-OBS"
setup_kw_dateut = "DATE-OBS"
